name: Hibiki CI/CD

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Run Rust Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Protobuf Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run Tests
        run: cargo test --verbose
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image (without pushing)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: hibiki:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PAT_TOKEN=${{ secrets.PAT_TOKEN }}

      - name: Display build time
        run: |
          echo "Docker build completed successfully"
          echo "Image built: hibiki:test"
